### ISSUE TITLE
rcov ruby 2.x

### ISSUE THREAD

**Issue by CirrusThink** [relevance/rcov#101]
I understand that rcov is not supported in ruby 2.x, and that is ok. What really is driving me insane is a way to figure out during bundle install which gem ir requesting the installation of gem rcov 0.9.11 ! I don't have anywhere in Gemfile the explicit request of gem 'rcov' ...
Is there a way to figure out which gem in Gemfile needs rcov as a dependency and is there a way to suggest in Gemfile to use a different gem to replace it ?

**Comment by abedra** [comment]
Take a look at Gemfile.lock to see the dependency tree and figure out what is causing this.

**Comment by CirrusThink** [comment]
There is no Gemfile.lock I need to buncle install to generate it
