### ISSUE TITLE
undefined method 'num_lines' errror

### ISSUE THREAD

**Issue by feurio** [relevance/rcov#11]
After an update from rcov 0.8.1.2.0 to relevance-rcov 0.8.3.2 I get the following error. Before the update everything did run fine.
The tests are started with a rake task...

erb):33:in `get_binding': undefined method`num_lines' for <Rake::FileTask  => []>:Rake::FileTask (NoMethodError)  
        from /usr/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov/formatters/html_erb_template.rb:122:in `get_binding'                                           
        from /usr/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov/formatters/html_erb_template.rb:20:in`render'  
        from /usr/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov/formatters/html_coverage.rb:93:in `create_file'                                                
        from /usr/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov/formatters/html_coverage.rb:93:in`open'  
        from /usr/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov/formatters/html_coverage.rb:93:in `create_file'                                                
        from /usr/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov/formatters/html_coverage.rb:31:in`execute'  
        from /usr/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov/formatters/base_formatter.rb:58:in `each'                                                      
        from /usr/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov/formatters/base_formatter.rb:58:in`each_file_pair_sorted'  
        from /usr/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov/formatters/html_coverage.rb:30:in `execute'                                                    
        from /usr/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov.rb:661:in`dump_coverage_info'  
        from /usr/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov.rb:661:in `each'                                                                               
        from /usr/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov.rb:661:in`dump_coverage_info'  
        from /usr/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/bin/rcov:402  
        from /usr/lib/ruby/gems/1.8/gems/rspec-1.2.6/lib/spec/runner.rb:45
rake aborted!

**Comment by spicycode** [comment]
What formatter are you using?  (HTML, Text, etc)

**Comment by feurio** [comment]
HTML

**Comment by spicycode** [comment]
What version (ruby -v) of ruby are you using as well?   We are still trying to track this down.  Also, if you could put in they way you are calling it from the rake task (the task definition) that would be very helpful.

**Comment by feurio** [comment]
I am using ruby 1.8.7 patchlevel 72 on Ubuntu Linux 8.04 with kernel 2.6.27-11-generic.

And here the rake task we are using:

desc "Run rspec test with rcov"
    Spec::Rake::SpecTask.new(:spec_local) do |t|

```
  # exclude the selenium tests from the standard rspec tests for cruise-control
  t.spec_files = FileList.new(['spec/**/*_spec.rb']) do | fl |
    fl.exclude(/spec\/integration\/selenium/)
  end

  # enable code coverage reporting
  t.rcov = true
  t.rcov_opts = ['--exclude', 'spec,/usr/lib/ruby,/usr/local/lib,db/*,config/*,stories/*,lib/*', '--rails' ]
  t.rcov_dir =  'rcov'

  # configure rspec
  t.spec_opts = ['--colour', '--reverse', '--loadby', 'mtime', '--format', 'progress']
end
```

**Comment by abedra** [comment]
This was fixed by mchung and added in 0.8.3.4

**Comment by feurio** [comment]
I cannot find this version via 'gem install' . Just the 0.8.3.3 version...
Would love to test if this works for me. Thanks for fixing the bug!

**Comment by abedra** [comment]
It's up now.  It took a while for the gem builder to get it pushed out.

**Comment by feurio** [comment]
Yeah. Found it out myself. Works like a charm. Thanks. 
Hope the change from standard rcov to relevance rcov gets rid of those mysterious and random seg faults in our cruise control builds...

**Comment by abedra** [comment]
It should.  That was one of the first things that got fixed when the project was taken over.
