### ISSUE TITLE
Jruby gem doesn't install

### ISSUE THREAD

**Issue by mattkanwisher** [relevance/rcov#12]
matthew-campbells-macbook-2:cms_trunk hyper$ jruby -S gem install relevance-rcov --source http://gems.github.com
Building native extensions.  This could take a while...
//jruby-1.2.0/lib/ruby/1.8/mkmf.rb:7: JRuby does not support native extensions. Check wiki.jruby.org for alternatives. (NotImplementedError)
    from //jruby-1.2.0/lib/ruby/1.8/mkmf.rb:1:in `require'
    from extconf.rb:1
ERROR:  Error installing relevance-rcov:
    ERROR: Failed to build gem native extension.

/jruby-1.2.0/bin/jruby extconf.rb install relevance-rcov --source http://gems.github.com

Gem files will remain installed in /jruby-1.2.0/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2 for inspection.
Results logged to /jruby-1.2.0/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/ext/rcovrt/gem_make.out

**Comment by spicycode** [comment]
The Jruby gem has moved to jruby-rcov.  You should be able to jruby -S gem install jruby-rcov to get a working install.
