### ISSUE TITLE
It is not possible to run rcov without specified formatters

### ISSUE THREAD

**Issue by valo** [relevance/rcov#14]
In my case I want to run rcov across several projects, aggregate the data and output the final result. I am not able to do that, because without any formatters rcov says there are no files covered.

For a fix see http://github.com/valo/rcov/commit/cc156482a7a4efa4a3f53dfca3a78d1d4fcccbb1

**Comment by abedra** [comment]
Great I'll take a look at it. Thanks for the input

**Comment by ghost** [comment]
'

**Comment by valo** [comment]
I can't understand what is the real status of this issue? Is it going to be fixed? Sorry, I am just not used to github's issue tracking

**Comment by ghost** [comment]
Hmmm, strange.  I didn't mean to close this issue, and I certainly didn't just put a quote for a comment :( 

What I tried to put in was that I will take a look at your branch.  If things look good I will pull the changes in.  Sorry for the confusion.
