### ISSUE TITLE
String with percent ('%') cause over reporting of coverage

### ISSUE THREAD

**Issue by jimweirich** [relevance/rcov#15]
The following program will be reported with 100% code coverage, even the untested method that is never called:

```
# Test this with:
#    rcov -x rcov.rb rcov_percent_bug.rb
#
# Bug: Rcov reports that this file is 100% covered (even the untested
# method that is never called).

class FooClass
  def tested
    # Change the percent to some other character and you get correctly
    # reported coverage.
    return "%"
  end

  def untested
    return nil
  end
end

FooClass.new.tested
```

**Comment by spicycode** [comment]
Jim, I'm looking into this now, what version and patch level of ruby are you running this under?

**Comment by jimweirich** [comment]
$  ruby --version
ruby 1.8.6 (2008-08-11 patchlevel 287) [universal-darwin9.0]

**Comment by abedra** [comment]
Jim,

I think I have found the issue here.  There is a slight discrepancy in callsite that seems to be surfacing here.  I will get this formalized into a test and try to get it worked out.

**Comment by abedra** [comment]
Jim,

This issue has been solved.  It actually occured in rcov.rb around line 212-214 in the method that decides if a line is considered a multiline string.  The regex wasn't quite correct and it was considering the return "%" the start of a multiline string which explains everything after it being counted as covered. 

rcov version 0.8.3.9 includes the fix
