### ISSUE TITLE
wrong file in coverage output

### ISSUE THREAD

**Issue by josh-m-sharpe** [relevance/rcov#17]
I'm seeing this file in my coverage output when I don't think it should be since it is outside of the rails app

/usr/local/lib/site_ruby/1.8/rubygems/dependency_list.rb

**Comment by josh-m-sharpe** [comment]
Dug into the source and have tried tacking on: 

--exclude /.*dependency_list.rb/

to the end of the command, but same problem

**Comment by josh-m-sharpe** [comment]
I found a workaround with   '-x dependency_list.rb'

Still, shouldn't this be excluded by default since it's outside of the rails app?

**Comment by ghost** [comment]
No, any files that are encountered inside of a test run with rcov are counted.  We use the exclude lists for all projects to make sure that only the files we want get added to the coverage reports.
