### ISSUE TITLE
no implicit conversion from nil to integer

### ISSUE THREAD

**Issue by ghost** [relevance/rcov#2]
Heya,

I'm having problems running rcov in an rspec project - I always just get the following : 

/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:131:in `[]&rsquo;: no implicit conversion from nil to integer (TypeError)
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:131:in`wrap&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:90:in `write_text&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/default.rb:50:in`write&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:75:in `write_element&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:73:in`each&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:73:in `write_element&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/default.rb:31:in`write&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:75:in `write_element&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:73:in`each&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:73:in `write_element&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/default.rb:31:in`write&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:75:in `write_element&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:73:in`each&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:73:in `write_element&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/default.rb:31:in`write&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:75:in `write_element&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:73:in`each&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:73:in `write_element&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/default.rb:31:in`write&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:75:in `write_element&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:73:in`each&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:73:in `write_element&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/default.rb:31:in`write&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:117:in `write_document&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:111:in`each&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:111:in `write_document&rsquo;
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rexml/formatters/default.rb:28:in`write&rsquo;
/Library/Ruby/Gems/1.8/gems/httparty-0.4.3/lib/httparty/core_extensions.rb:22:in `write&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:92:in`pretty&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/report.rb:815:in `format_overview&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/report.rb:870:in`create_index&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:103:in `create&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:79:in`tracking_additions&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:102:in `create&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:371:in`x_&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/report.rb:870:in `create_index&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:103:in`create&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:79:in `tracking_additions&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:102:in`create&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:492:in `body_&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:239:in`send&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:239:in `method_missing&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/report.rb:860:in`create_index&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:103:in `create&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:79:in`tracking_additions&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:102:in `create&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:492:in`html_&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:239:in `send&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:239:in`method_missing&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/report.rb:849:in `create_index&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:290:in`call&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:290:in `xx_with_doc_in_effect&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:575:in`xhtml_&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:276:in `xx_which&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/xx.rb:574:in`xhtml_&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/report.rb:849:in `create_index&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov/report.rb:723:in`execute&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov.rb:640:in `dump_coverage_info&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov.rb:640:in`each&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov.rb:640:in `dump_coverage_info&rsquo;
/Library/Ruby/Gems/1.8/gems/spicycode-rcov-0.8.2.1/bin/rcov:408
 @@@

I&rsquo;m running on OS X 10.5.6, with ruby 1.8.6 (2008-03-03 patchlevel 114) [universal-darwin9.0], and spicycode-rcov 0.8.2.1.

Any suggestions?

[original LH ticket](http://relevance.lighthouseapp.com/projects/16869/tickets/14)

 This ticket has 0 attachment(s).

**Comment by spicycode** [comment]
This should be resolved by version 0.8.3.2
