### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by jeffshadap** [relevance/rcov#20]
gem install relevance-rcov

Building native extensions.  This could take a while...
ERROR:  Error installing relevance-rcov:
        ERROR: Failed to build gem native extension.

c:/ruby/bin/ruby.exe extconf.rb
c:/ruby/bin/ruby.exe: No such file or directory -- extconf.rb (LoadError)

Gem files will remain installed in c:/ruby/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.4 for inspection.
Results logged to c:/ruby/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.4/ext/rcovrt/gem_make.out

**Comment by ghost** [comment]
We do not currently support windows with this version of rcov.  We don't use windows day to day and don't feel that we are the best team to support it.  If you are interested please feel free to fork this version.
