### ISSUE TITLE
Rcov::BaseFormatter requires mkmf?

### ISSUE THREAD

**Issue by robg** [relevance/rcov#21]
I was seeing really strange errors in my tests with the latest version of rcov, which I finally tracked down to a method named message(*s) that is defined in mkmf.rb and being pulled in by BaseFormatter: http://github.com/relevance/rcov/blob/f32ce770c31bdcc6dd1aa432c6074425246535f5/lib/rcov/formatters/base_formatter.rb#L5 

I tried commenting out the require which fixed my immediate problem, and I was still able to generate the coverage report.  Is mkmf really required?

Cheers

**Comment by ghost** [comment]
mkmf is required to install rcov.  It is responsible for handling the C extension portion of the install.  I will look into the requirement in the base formatter, I don't think it actually needs to be there.

**Comment by ghost** [comment]
This is fixed now.  I just pushed version 0.8.3.5.

**Comment by robg** [comment]
Hey - I see where you had to add mkmf back into BaseFormatter.  Maybe I'm missing something, but is it true that its only purpose is to provide access to the Config module? What about just requiring rbconfig directly instead of going through mkmf?

Thanks

rob

**Comment by ghost** [comment]
I had to add the requirement back in as a quick fix.  This is not a permanent solution, however, it really doesn't impact anyone since you need mkmf to install RCov.  I will be pulling out the mkmf requirement and replacing it with a better solution in the somewhat near future
