### ISSUE TITLE
RCov does not seem to escape HTML

### ISSUE THREAD

**Issue by vrinek** [relevance/rcov#22]
my code: http://gist.github.com/156415
part of the html coverage output: http://gist.github.com/156416

As you can see, the html renderer does not escape the html tags inside my code messing up the html output.

**Comment by abedra** [comment]
Ouch!  I'll get that fixed up right away!

**Comment by ghost** [comment]
This has been fixed in version 0.8.3.8.  You can download and build it from source or wait for github to generate the new gem.
