### ISSUE TITLE
rcov failing with NoMethodError - nil object when you didn't expect it

### ISSUE THREAD

**Issue by cgoddard** [relevance/rcov#23]
I keep getting this error when trying to run rcov with rspec.  rcov version 0.8.3.8, rspec version 1.2.8.  Let me know if you need more information.

/usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.8/lib/rcov.rb:675:in `aggregate_data': You have a nil object when you didn't expect it! (NoMethodError)
You might have expected an instance of Array.
The error occurred while evaluating nil.+
    from /usr/local/lib/ruby/gems/1.8/gems/rspec-1.2.8/lib/spec/runner.rb:45:in`each_with_index'
    from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.8/lib/rcov.rb:675:in `each'
    from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.8/lib/rcov.rb:675:in`each_with_index'
    from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.8/lib/rcov.rb:675:in `aggregate_data'
    from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.8/lib/rcov.rb:673:in`each_pair'
    from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.8/lib/rcov.rb:673:in `aggregate_data'
    from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.8/lib/rcov.rb:511:in`raw_data_relative'
    from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.8/lib/rcov.rb:452:in `remove_hook'
    from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.8/lib/rcov.rb:639:in`remove_hook'
    from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.8/bin/rcov:411
    from /usr/local/lib/ruby/gems/1.8/gems/rspec-1.2.8/lib/spec/runner.rb:45
rake aborted!
Command /usr/local/bin/ruby -I"/usr/local/lib/ruby/gems/1.8/gems/rspec-1.2.8/lib" -S rcov --rails --exclude "spec/_,gems/_,features/*" --aggregate coverage.data -o "coverage" -o "coverage" "/usr/local/lib/ruby/gems/1.8/gems/rspec-1.2.8/bin/spec" -- "spec/models/molecular/matrix_spec.rb" --options "/home/cgoddard/Working_copies/mi0508/spec/spec.opts" failed
/usr/local/lib/ruby/gems/1.8/gems/rspec-1.2.8/lib/spec/rake/spectask.rb:177:in `define'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1112:in`verbose'
/usr/local/lib/ruby/gems/1.8/gems/rspec-1.2.8/lib/spec/rake/spectask.rb:153:in `define'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`call'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`each'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in`invoke_with_call_chain'
/usr/local/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in`invoke_with_call_chain'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in`invoke_task'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`each'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in`run'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in`run'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
/usr/local/bin/rake:19:in `load'
/usr/local/bin/rake:19

**Comment by abedra** [comment]
Interesting...

There is more than likely a bug here, but I will need a little more context as to how you got here.  Can you provide some sample code that demonstrates the same failure?

**Comment by cgoddard** [comment]
I was able to fix the issue by deleting the old coverage.data file and running rcov again.  Maybe the file became corrupted somehow.

**Comment by cgoddard** [comment]
I have a copy of the file if that would be helpful.

**Comment by jdamick** [comment]
see: http://jira.codehaus.org/browse/JRUBY-2852   for a fix

**Comment by abedra** [comment]
Thanks!  I will pull that in today.

**Comment by ghost** [comment]
It looks like the fix above doesn't actually apply here.  The original problem posted is not the same as the jruby bug.  There still might be a bug here, but since the poster has been able to resolve the issue I am going to close this.

**Comment by suranyami** [comment]
I'm still getting this bug in 0.9.0. The array iteration should implement some checks for nils, and continue processing harmlessly.

**Comment by ghost** [comment]
This issue is closed.  If you are having a problem please open a new issue and include an example

**Comment by evanworley** [comment]
I'm still getting that issue, opening a new issue
