### ISSUE TITLE
Rcov fails when it encounters content_for in a source file

### ISSUE THREAD

**Issue by CoralineAda** [relevance/rcov#25]
The error I get:

/Library/Ruby/Gems/1.8/gems/relevance-rcov-0.8.6/lib/rcov/formatters/html_erb_template.rb:37:in `method_missing': undefined method`content_for' for #Rcov::Formatters::HtmlErbTemplate:0x4aaa344 (NoMethodError)
from /Users/bantik/Documents/projects/toolbox/_application/vendor/plugins/redacted/lib/redacted/extensions.rb:254:in `title'

The title method in extensios.rb contains a call to content_for. If I remove that line from extensions.rb, there's no trouble. Running RSpec without RCov does not show any errors.

**Comment by abedra** [comment]
I will take a look into this soon.

**Comment by abedra** [comment]
can you provide a better example?  maybe something that is easier to reproduce?

**Comment by CoralineAda** [comment]
Sure thing. What would be more helpful: a single source file or a sample Rails project?

**Comment by abedra** [comment]
A sample rails app would be the most helpful.  I have been keeping a collection of apps that are failing as references for bugfixes.  The less time I have to take to reproduce the errors the more time I can spend fixing them :)

**Comment by CoralineAda** [comment]
I uploaded a stub app that demonstrates the problem as a private repo... you should have an invite.

**Comment by CoralineAda** [comment]
Note that the tests for the app all pass; the problem emerges when RCov comes into the picture. It seems like RCov is trying to evaluate the code in the source file and ends up looking for a method called content_for in Rcov::Formatters::HtmlErbTemplate.

Full stack trace:

/Library/Ruby/Gems/1.8/gems/relevance-rcov-0.8.6/lib/rcov/formatters/html_erb_template.rb:37:in `method_missing': undefined method`content_for' for #Rcov::Formatters::HtmlErbTemplate:0x254db8c (NoMethodError)
    from /Users/bantik/Documents/projects/stub_for_rcov/app/helpers/application_helper.rb:49:in `title'
    from (erb):4:in`get_binding'
    from /Library/Ruby/Gems/1.8/gems/relevance-rcov-0.8.6/lib/rcov/formatters/html_erb_template.rb:41:in `get_binding'
    from /Library/Ruby/Gems/1.8/gems/relevance-rcov-0.8.6/lib/rcov/formatters/html_erb_template.rb:18:in`render'
    from /Library/Ruby/Gems/1.8/gems/relevance-rcov-0.8.6/lib/rcov/formatters/html_coverage.rb:78:in `create_index'
    from /Library/Ruby/Gems/1.8/gems/relevance-rcov-0.8.6/lib/rcov/formatters/html_coverage.rb:78:in`open'
    from /Library/Ruby/Gems/1.8/gems/relevance-rcov-0.8.6/lib/rcov/formatters/html_coverage.rb:78:in `create_index'
    from /Library/Ruby/Gems/1.8/gems/relevance-rcov-0.8.6/lib/rcov/formatters/html_coverage.rb:27:in`execute'
    from /Library/Ruby/Gems/1.8/gems/relevance-rcov-0.8.6/lib/rcov/code_coverage_analyzer.rb:146:in `dump_coverage_info'
    from /Library/Ruby/Gems/1.8/gems/relevance-rcov-0.8.6/lib/rcov/code_coverage_analyzer.rb:146:in`each'
    from /Library/Ruby/Gems/1.8/gems/relevance-rcov-0.8.6/lib/rcov/code_coverage_analyzer.rb:146:in `dump_coverage_info'
    from /Library/Ruby/Gems/1.8/gems/relevance-rcov-0.8.6/bin/rcov:422
    from /Library/Ruby/Gems/1.8/gems/rspec-1.2.7/lib/spec/runner.rb:45
rake aborted!
Command /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby -I"/Library/Ruby/Gems/1.8/gems/rspec-1.2.7/lib" -S rcov --exclude "spec/_,gems/_,/Library/*" --rails -o "coverage" "/Library/Ruby/Gems/1.8/gems/rspec-1.2.7/bin/spec" -- "spec/controllers/access_control_spec.rb" "spec/controllers/application_controller_spec.rb" "spec/controllers/authenticated_system_spec.rb" "spec/controllers/home_controller_spec.rb" "spec/controllers/roles_controller_spec.rb" "spec/controllers/sessions_controller_spec.rb" "spec/controllers/users_controller_spec.rb" "spec/helpers/application_helper_spec.rb" "spec/helpers/users_helper_spec.rb" "spec/models/notifier_spec.rb" "spec/models/role_spec.rb" "spec/models/user_spec.rb" --options "/Users/bantik/Documents/projects/stub_for_rcov/spec/spec.opts" failed

**Comment by ghost** [comment]
Thanks!  I will check this out and see what I can find.  I imagine it should be pretty obvious based on what you have described.

**Comment by abedra** [comment]
closing this issue after talking with @Bantik and confirming that the issue can no longer be reproduced
