### ISSUE TITLE
Too many red lines using rcov with Ruby 1.9.1

### ISSUE THREAD

**Issue by rggjan** [relevance/rcov#29]
Using the following two files:

1 require 'testobject'
2 require 'test/unit'
3 
4 class MyTest < Test::Unit::TestCase
5 
6   def test_object
7     a = TestObject.new
8     assert_equal "Test", a.to_s
9   end
10 
11 end

1 require 'testobject'
2 require 'test/unit'
3 
4 class MyTest < Test::Unit::TestCase
5 
6   def test_object
7     a = TestObject.new
8     assert_equal "Test", a.to_s
9   end
10 
11 end

rcov misses to paint green the following lines:

with rcovrt:
test.rb: 1, 4, 6
testobject.rb: 1, 4, 5

without rcovrt:
test.rb: everything ok!
testobject.rb: 6, 7

Below the report with my specs...
# 

Bug report generated on 2009-09-18 13:14:03 +0200

Ruby version:              1.9.1 (2009-07-16)
Platform:                  i686-linux
rcov version:              0.9.1.1
rcovrt loaded?             false
using RubyGems?            true
Command-line arguments:    ["-I", "./testobject.rb", "--no-rcovrt", "--report-cov-bug=TestObject#to_s", "./test.rb"]
Coverage analysis bug in:  TestObject#to_s

Line(s) ____________ should be ______ (red/green).

Raw coverage information (feel free to remove useless data, but please leave
some context around the faulty lines):

```
  3:    5:  def to_s
  0:    6:    return "Test"
  0:    7:  end
  1:    8:end
```

**Comment by ghost** [comment]
Yes, The 1.9 support isn't quite there yet.  --no-rcovrt will be the most accurate solution for 1.9, but isn't all the way there.

**Comment by wagenet** [comment]
I tried using the --no-rcovrt option and got this failure:

/Users/peterwagenet/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/code_coverage_analyzer.rb:160:in `+': nil can't be coerced into Fixnum (TypeError)
    from /Users/peterwagenet/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/code_coverage_analyzer.rb:160:in`block (2 levels) in aggregate_data'
    from /Users/peterwagenet/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/code_coverage_analyzer.rb:160:in `each'
    from /Users/peterwagenet/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/code_coverage_analyzer.rb:160:in`each_with_index'
    from /Users/peterwagenet/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/code_coverage_analyzer.rb:160:in `block in aggregate_data'
    from /Users/peterwagenet/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/code_coverage_analyzer.rb:158:in`each_pair'
    from /Users/peterwagenet/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/code_coverage_analyzer.rb:158:in `aggregate_data'
    from /Users/peterwagenet/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/differential_analyzer.rb:112:in`raw_data_relative'
    from /Users/peterwagenet/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/differential_analyzer.rb:52:in `remove_hook'
    from /Users/peterwagenet/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/code_coverage_analyzer.rb:124:in`remove_hook'
    from /Users/peterwagenet/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/relevance-rcov-0.9.2.1/bin/rcov:425:in `block in <top (required)>'
rake aborted!

**Comment by wagenet** [comment]
I changed relevance-rcov-0.9.2.1/lib/rcov/code_coverage_analyzer.rb:160 from
  cov_arr.each_with_index{|x,i| dest[i] += x}
to:
  cov_arr.each_with_index{|x,i| dest[i] += x.to_i}

This seems to fix it and gives much more expected results.

**Comment by ghost** [comment]
This error is along similar lines as another older ticket.  I am going to close this one in favor of the longer running ticket.  This will be fixed in the next release
