### ISSUE TITLE
method definition lines are uncolored

### ISSUE THREAD

**Issue by benhutton** [relevance/rcov#33]
In my output, the method definition lines are never colored or counted.  For example,

Line 1: def to_param
Line 2:   self.id
Line 3: end

Line 1 is not counted, but lines 2 and 3 are.  This is clearly wrong: if 2 and 3 are counted, then 1 should be counted as well.

FYI, I'm running Rails 2.3.4 on Ruby 1.9.1 p243 on rcov 0.9.2.1

**Comment by ghost** [comment]
This issue has already been reported.  There are issues with the C version of RCov on 1.9.1.  To get more accurate coverage add the --no-rcovrt option.  This issue belongs on the 1.9.1 compatibility ticket and is being closed.
