### ISSUE TITLE
Setting --text-summary causes --failure-threshold to be ignored

### ISSUE THREAD

**Issue by rsanheim** [relevance/rcov#34]
When running rcov with a --failure-threshold, if you _also_ pass in --text-summary to specify the reporting option, the failure threshold is ignored and will never fail the build.  Removing --text-summary results in failure threshold being correctly applied.

So these options do not fail a build (at 95% coverge):

```
rcov -Ilib -Ispec --exclude "features/*,spec/*,gems/*,lib/authenticated*,db/*,/Library/Ruby/*,.ruby_versions/*,config/*" --rails --failure-threshold 96.0 --text-summary --sort coverage -Ilib -Ispec 
```

And these options do fail:

```
rcov -Ilib -Ispec --exclude "features/*,spec/*,gems/*,lib/authenticated*,db/*,/Library/Ruby/*,.ruby_versions/*,config/*" --rails --failure-threshold 96.0 --sort coverage -Ilib -Ispec
```

Note that just specifying --text-report results in the threshold being ignored.  So it appears setting any sort of output option at all results in the failure threshold being ignore.

Thanks,
Rob

**Comment by hooligan495** [comment]
I too ran into this problem and implemented a fix in my branch... hooligan495/rcov where we accept multiple formatters.  Is there a better way to fix this? 
Thanks!
