### ISSUE TITLE
Code Coverage reporting on Partials is inconsistent on MRI and JRuby

### ISSUE THREAD

**Issue by hooligan495** [relevance/rcov#35]
I have been looking into some oddities with code coverage on rails partials.  In Jruby I can get RCov to report code coverage results for partials.  but running under MRI I can't... I am not exactly sure what the correct behavior should be (I would assume it's better to have more coverage).  I am going to continue investigating this.

**Comment by hooligan495** [comment]
here is the code I am using to investigate this issue:
http://github.com/hooligan495/partials-rcov

**Comment by jason-o-matic** [comment]
I can't seem to get rcov to report on views of any kind, template or partial.  I checked out the repo you linked to, and it didn't work for me either.  I'm on rcov 0.9.8.  Is there a trick to getting some kind of view coverage at all?

**Comment by hooligan495** [comment]
is this in regular ruby? or Jruby?  I hope to spend more time on this issue next week...

**Comment by jason-o-matic** [comment]
MRI ruby 1.8.6 (2009-06-08 patchlevel 369) [universal-darwin9.0]
