### ISSUE TITLE
running tests in gem

### ISSUE THREAD

**Issue by mdkent** [relevance/rcov#36]
Packaging rcov for a Fedora submission and would like to run the tests as part of the build process. The stumbling block seems to be some key files are missing from the gem, specifically: test_helper.rb, assets/sample_06.rb and expected_coverage/*. Once added the tests pass just fine.

Would it be possible to include these in the gem?

**Comment by ghost** [comment]
Sure. These just need to be added to the gem spec files for both platforms.  Can you add what is needed and send a patch?

**Comment by Flameeyes** [comment]
As an alternative would be nice to have tags for the releases, so that distributions (in my case, Gentoo, and we have the same problem) can just use the tarball for doing the packaging.

Pretty please!

**Comment by ghost** [comment]
Ok I pushed version 0.9.7 to gemcutter and tagged the release.  This should resolve both issues.

Aaron
