### ISSUE TITLE
HTML display can't handle filenames like "<script>"

### ISSUE THREAD

**Issue by jcoyne** [relevance/rcov#37]
The < and > aren't being escaped.  Jruby sends this string when evalScriptlet() is called.

**Comment by hooligan495** [comment]
Jruby adds filenames to Scriptlines that are a bit "odd".  some names are : (eval) (erb) &lt;script&gt; yaml.  I do not think that MRI does a similar thing.  So we could accept the patch that Justin submitted... or we could modify rcov to always exclude a certain set of "files" that are in the list of files mentioned above.  I think Justin's patch would be beneficial for more than just script.  On windows we are seeing problems when rcov tries to generate filenames with odd syntaxes.  (ie a filename with a : in it)

**Comment by abedra** [comment]
The provided patch should use the built in CGI escape method.  An example can be found in the RCov source:

opensource/rcov/master > ack CGI 
lib/rcov/templates/detail.html.erb
55:            <td><pre><a name="line<%= i.next %>"><%= i.next %></a> <%= CGI::escapeHTML(line) %></pre></td>
opensource/rcov/master > 

This should absolutely be resolved.  If either of you can get to this before I can please submit a pull request.
