### ISSUE TITLE
rcov 0.9.7 fails tests

### ISSUE THREAD

**Issue by Flameeyes** [relevance/rcov#40]
/usr/bin/ruby18 -I"lib:ext/rcovrt" "/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader.rb" "test/file_statistics_test.rb" "test/call_site_analyzer_test.rb" "test/code_coverage_analyzer_test.rb" "test/functional_test.rb" 
Loaded suite /usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader
Started
............F.F..F...........................
Finished in 2.185891 seconds.

  1) Failure:
test_differential_coverage_data(TestCodeCoverageAnalyzer) [./test/code_coverage_analyzer_test.rb:125]:
<[0, 1, 1, 1, 0]> expected but was
<[0, 1, 2, 0, 0]>.

  2) Failure:
test_nested_analyzer_blocks(TestCodeCoverageAnalyzer) [./test/code_coverage_analyzer_test.rb:190]:
<[0, 221, 221, 221, 0]> expected but was
<[0, 221, 442, 0, 0]>.

  3) Failure:
test_reset(TestCodeCoverageAnalyzer) [./test/code_coverage_analyzer_test.rb:208]:
<[0, 50, 50, 50, 0]> expected but was
<[0, 50, 100, 0, 0]>.

45 tests, 444 assertions, 3 failures, 0 errors
rake aborted!
Command failed with status (1): [/usr/bin/ruby18 -I"lib:ext/rcovrt" "/usr/l...]

If you need specific information let me know.

**Comment by abedra** [comment]
RCov is running it's continuous integration on RunCodeRun and the builds are passing.  Here are the links to the MRI and JRuby builds

http://runcoderun.com/relevance/rcov/builds/058478984574401d3002d545f7c97f49cec1b754/1/jruby_130

http://runcoderun.com/relevance/rcov/builds/058478984574401d3002d545f7c97f49cec1b754/1/ruby_186

**Comment by abedra** [comment]
Are you running the version of Ruby that is bundled with Snow Leopard?  If so that version is broken and causes test failures in the RCov suite.

**Comment by Flameeyes** [comment]
Nope, Gentoo Linux is what I'm using (and packaging for).

**Comment by abedra** [comment]
I'm more than happy to take a look at this if you can provide me more info about how you have things setup and what versions of ruby you are trying the build against.  Please do take a look at the RunCodeRun build status for build failures in the future though.

**Comment by Flameeyes** [comment]
This is ruby-1.8.7_p248, that might be the problem (RunCodeRun seem to be using 1.8.6 instead).

On Ruby 1.9 I get even more failures, but interestingly, there, instead of merging the second and third value, it's the first and the second to be merged,  it seems.

**Comment by abedra** [comment]
The tests for 1.9 are known to fail.  The 1.9 support is mostly experimental at the moment.  As far as 1.8.7 is concerned I can take another look.  The last time I checked the tests were passing, but things could have changed.

**Comment by stahnma** [comment]
I'm also seeing these same failures on 1.8.7 on RHEL6 beta.  ruby-1.8.7.299.  I am working on packaging for RHEL6.  This is on rcov-0.9.9

**Comment by stahnma** [comment]
Was this fixed, or was the issue just closed?

**Comment by graaff** [comment]
As far as I can tell this issue was only closed. I still get these test failures with rcov 0.9.11.
