### ISSUE TITLE
rcov git fails tests with JRuby 1.4.0

### ISSUE THREAD

**Issue by Flameeyes** [relevance/rcov#44]
Started
...............F.............................
Finished in 45.491 seconds.

  1) Failure:
test_raw_coverage_info(TestCodeCoverageAnalyzer) [./test/code_coverage_analyzer_test.rb:52]:
<[1, 3, 0, 0, 1, 0, 33]> expected but was
<[1, 3, 0, 0, 1, 0, 13]>.

45 tests, 446 assertions, 1 failures, 0 errors
rake aborted!
Command failed with status (1): [/usr/share/jruby/bin/jruby -I"lib:lib" --d...]

(See full trace by running task with --trace)

This happens both with the default-provided jar file and with a rebuilt one.

**Comment by ghost** [comment]
This issue has been resolved as of 0.9.8.
