### ISSUE TITLE
rcov_save_aggregate_data fails because directory doesn't exist

### ISSUE THREAD

**Issue by garysweaver** [relevance/rcov#45]
Apologize in advance if this is not a bug, but just in case it helps...

When running rcov-0.9.7.1-java (JRuby 1.4.0 compatible version of rcov-0.9.7.1), rcov_save_aggregate_data fails (in bin/rcov) because the coverage directory does not exist yet when it tries to create the aggregate.data file in that directory.

To fix this, I added the following line:
    FileUtils.mkdir_p(File.dirname(file)) unless File.exist?(File.dirname(file))

So that the method looks like:
    def rcov_save_aggregate_data(file)
      require 'zlib'
      FileUtils.mkdir_p(File.dirname(file)) unless File.exist?(File.dirname(file))
      Zlib::GzipWriter.open(file) do |f|
        Marshal.dump({:callsites => $rcov_callsite_analyzer, :coverage => $rcov_code_coverage_analyzer}, f)
      end
    end

I noticed that the same code exists in this Ruby 1.9 compatible version of rcov, but I don't have the environment setup right now to test my project with relevance's rcov fork along with JRuby 1.4.0 and JRuby's Ruby 1.9 support turned on in it. Perhaps you have that setup and could verify whether or not it is a bug and whether a fix similar to this might help?

The corresponding RubyForge rcov issue is http://bit.ly/bFHm7x

**Comment by ghost** [comment]
How are you invoking rcov?  Are you using the built in rake tasks or rspec coverage tasks?  I have projects running on every version of ruby (including JRuby) and have not seen this come up.  Any more information you have would be much appreciated.

Also please note that the rubyforge project for RCov is very old and very abandoned.

**Comment by garysweaver** [comment]
iirc (but it was a month ago so I might be wrong), I was invoking it via an option in Hudson ( http://hudson-ci.org/ ). We are also using the Ruby-metrics plugin ( http://wiki.hudson-ci.org/display/HUDSON/Ruby+metrics+plugin ) that kicks off rcov. In addition, iirc this is being run via rcov-0.9.7.1-java (JRuby 1.4.0 compatible version of rcov-0.9.7.1) in the JRuby 1.4.0 that RVM (Ruby Version Manager: http://rvm.beginrescueend.com/ ) provides, although I doubt the latter makes much difference. My guess is that rcov is expecting the coverage directory to have been created, but that code is either not being called in this environment, or possibly it gets created but then Hudson creates a temporary build directory in which the coverage directory does not exist before rcov is called. Basically, it just might be helpful to check for the existence of the directory and attempt to create it if it isn't there, but I understand if you don't want to do that, and I understand that you'd like to be able to reproduce the issue. Sorry I can't be of more help.

**Comment by bkimble** [comment]
Pretty old issue, but just in case someone gets redirected here like me -- the issue may be that the first thing RcovTask does it remove the directory (calls the clobber tasks).
