### ISSUE TITLE
Problem with I18n.

### ISSUE THREAD

**Issue by DAddYE** [relevance/rcov#46]
HI,

I've the following problem with rcov and I18n.

<pre>
/Library/Ruby/Gems/1.8/gems/i18n-0.3.3/lib/i18n/core_ext/string/interpolate.rb:91:in `interpolate_without_ruby_19_syntax': illegal format character - % (ArgumentError)
    from /Library/Ruby/Gems/1.8/gems/i18n-0.3.3/lib/i18n/core_ext/string/interpolate.rb:91:in `send'
    from /Library/Ruby/Gems/1.8/gems/i18n-0.3.3/lib/i18n/core_ext/string/interpolate.rb:91:in `%'
    from /Library/Ruby/Gems/1.8/gems/relevance-rcov-0.9.2.1/lib/rcov/formatters/text_summary.rb:8:in `summary'
    from /Library/Ruby/Gems/1.8/gems/relevance-rcov-0.9.2.1/lib/rcov/formatters/text_report.rb:17:in `execute'
    from /Library/Ruby/Gems/1.8/gems/relevance-rcov-0.9.2.1/lib/rcov/code_coverage_analyzer.rb:146:in `dump_coverage_info'
    from /Library/Ruby/Gems/1.8/gems/relevance-rcov-0.9.2.1/lib/rcov/code_coverage_analyzer.rb:146:in `each'
    from /Library/Ruby/Gems/1.8/gems/relevance-rcov-0.9.2.1/lib/rcov/code_coverage_analyzer.rb:146:in `dump_coverage_info'
    from /Library/Ruby/Gems/1.8/gems/relevance-rcov-0.9.2.1/bin/rcov:428
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/test/unit.rb:278
rake aborted!
Command failed with status (1): [/System/Library/Frameworks/Ruby.framework/...]
</pre>

**Comment by abedra** [comment]
Please submit this bug with a failing test case that supports your claim. Please include your Ruby version and patchlevel, along with your operating system version, and version of gcc
