### ISSUE TITLE
`get_binding': undefined method `num_lines' for 3:Fixnum (NoMethodError)

### ISSUE THREAD

**Issue by shirzad** [relevance/rcov#48]
Hi,
(erb):54:in `get_binding': undefined method`num_lines' for 3:Fixnum (NoMethodError)
    from /Users/arbab/.rvm/rubies/ruby-1.9.1-p378/lib/ruby/1.9.1/erb.rb:753:in `eval'
    from /Users/arbab/.rvm/rubies/ruby-1.9.1-p378/lib/ruby/1.9.1/erb.rb:753:in`result'
    from /Users/arbab/.rvm/gems/ruby-1.9.1-p378/gems/rcov-0.9.8/lib/rcov/formatters/html_erb_template.rb:18:in `render'
    from /Users/arbab/.rvm/gems/ruby-1.9.1-p378/gems/rcov-0.9.8/lib/rcov/formatters/html_coverage.rb:97:in`block in create_index'
    from /Users/arbab/.rvm/gems/ruby-1.9.1-p378/gems/rcov-0.9.8/lib/rcov/formatters/html_coverage.rb:97:in `open'
    from /Users/arbab/.rvm/gems/ruby-1.9.1-p378/gems/rcov-0.9.8/lib/rcov/formatters/html_coverage.rb:97:in`create_index'
    from /Users/arbab/.rvm/gems/ruby-1.9.1-p378/gems/rcov-0.9.8/lib/rcov/formatters/html_coverage.rb:42:in `execute'
    from /Users/arbab/.rvm/gems/ruby-1.9.1-p378/gems/rcov-0.9.8/lib/rcov/code_coverage_analyzer.rb:146:in`block in dump_coverage_info'
    from /Users/arbab/.rvm/gems/ruby-1.9.1-p378/gems/rcov-0.9.8/lib/rcov/code_coverage_analyzer.rb:146:in `each'
    from /Users/arbab/.rvm/gems/ruby-1.9.1-p378/gems/rcov-0.9.8/lib/rcov/code_coverage_analyzer.rb:146:in`dump_coverage_info'
    from /Users/arbab/.rvm/gems/ruby-1.9.1-p378/gems/rcov-0.9.8/bin/rcov:428:in `block in <top (required)>'
rake aborted!
Command failed with status (1): [rcov --rails -Ilib:test --sort coverage --...]

I am getting this error while testing Rails 3.0.0.beta under rvm and ruby 1.9.1
I am using the rcov_plugin for my tasks.

**Comment by abedra** [comment]
RCov does not and will not support Ruby 1.9. Please use simple cov on 1.9+
