### ISSUE TITLE
rcov for Windows

### ISSUE THREAD

**Issue by pupeno** [relevance/rcov#49]
Hello,

Can you publish a binary gem for rcov for Windows please?

Thanks.

**Comment by ghost** [comment]
Windows is not currently supported.  If you would like to fork RCov and supply a binary along with a rake task to keep it up to date I would be more than happy to pull the changes in.  If you would like to do this and have questions feel free to send us a message.

**Comment by pupeno** [comment]
I'm not sure if I can do it. Windows is not my main development platform. Just for the record there's a way to cross-compile: http://www.copiousfreetime.org/articles/2008/10/12/building-gems-for-windows.html

**Comment by ghost** [comment]
This is the main reason I have not committed time to Windows.  It is not my main platform and I don't use it for any Ruby.  I am aware of the compile options, but I don't have a nice way to test builds out for different versions of windows.
