### ISSUE TITLE
Rcov doesn't report coverage on ruby loaded with class_eval and a file and line number

### ISSUE THREAD

**Issue by jason-o-matic** [relevance/rcov#51]
```
me@lappy partials-rcov $ cat test1.rb
self.class.class_eval(File.open("test2.rb") { |f| f.read }, "test2.rb", 0)
me@lappy partials-rcov $ cat test2.rb
puts "foo"
me@lappy partials-rcov $ rcov test1.rb
foo
```

This results in a report showing 100% coverage of test1.rb, but doesn't show test2.rb at all.  I would expect test2.rb to show up with 100% coverage as well since I supplied the file and line to class_eval.

It's been a few years since I've used rcov, but I could have sworn this used to work.

Am I missing something?  A flag I need to pass to rcov?  I tried it with --no-rcovrt just in case and that didn't work either.

**Comment by abedra** [comment]
This is a pretty tricky thing to make work properly. Ruby's internals have changed a bit. Since this case doesn't happen all that often and the move to 1.9 is pretty heavy, I don't think it's worth the time to fix this.
