### ISSUE TITLE
Slowing down cucumber test suite

### ISSUE THREAD

**Issue by diasjorge** [relevance/rcov#53]
With version 0.6.3 of cucumber rcov would not add much overhead to the total time of the test suite. A couple seconds only. Now I updated to version 0.7 of cucumber and it adds about 1.5 minutes.
Without rcov the suite takes 6.01 min. With rcov it takes 7.3 min

**Comment by abedra** [comment]
Nothing in rcov has changed to make this slow down. This is likely doue to a change in cucumber

**Comment by diasjorge** [comment]
After almost 2 years I don't event know what this issue is about
