### ISSUE TITLE
Code is not being escaped

### ISSUE THREAD

**Issue by pupeno** [relevance/rcov#54]
When the HTML is generated if there are angle brackets, since the code is not being escaped, the generated html is broken. If I can I'll attach some screenshots here.

**Comment by pupeno** [comment]
You can see the screenshots here:

http://imgur.com/868m2.png

http://imgur.com/NtoyV.png

**Comment by hooligan495** [comment]
This Issue is fixed in the master branch.  I am hoping to get Aaron to push a new release of RCov asap.

**Comment by pupeno** [comment]
Great :)

**Comment by hooligan495** [comment]
sorry for the delay in pushing... it looks like it is pushed but the jruby version is not installing correctly.  So I will close this and work on getting jruby to install properly
