### ISSUE TITLE
Allow merging of various rcov run aggregates?

### ISSUE THREAD

**Issue by antifuchs** [relevance/rcov#55]
I'd really like to be able to do coverage statistics for my cucumber features, which start an external HTTP server for some steps. This HTTP server is driven by a ruby instance running the cucumber steps. Both ruby instances simultaneously exercise different code paths, which I would like to count towards the total coverage.

My idea was to have each of these processes dump aggregate data into an aggregate file, and merge them at a time when all processes are done. Unfortunately, it seems that merging of CodeCoverageAnalyzers isn't implemented. Is there any chance this could be done?

**Comment by scottsymm** [comment]
+1

i am not sure that the --aggregate option would work for me, b/c i have multiple ruby processes running at once.

additionally, i'd like to be able to look at reports which have all tests, and ones where each test, or suite, is reported separately.

**Comment by abedra** [comment]
If you would like to implement this, please feel free to submit a pull request. This feature most likely won't be introduced into RCov by any of the maintainers.
