### ISSUE TITLE
incorrect coverage count with jruby when file has \r\n line endings

### ISSUE THREAD

**Issue by denofevil** [relevance/rcov#56]
this is bug in jruby, which is discussed on http://jira.codehaus.org/browse/JRUBY-4405. it is considered minor and fix will be available only on 1.6 branch

**Comment by denofevil** [comment]
I must add that this issue is very important for JetBrains RubyMine 2.5 upcoming release, I've sent a pull request with suggested fix.

**Comment by hooligan495** [comment]
I didn't see a pull request... can you send it to me?  (sorry for not seeing this sooner)

**Comment by hooligan495** [comment]
nevermind I found your commit and have added it (but not yet pushed it)

**Comment by denofevil** [comment]
thank you very much!

sorry for the late reply, I was on my wedding trip =)

**Comment by hooligan495** [comment]
congratulations!

**Comment by rsanheim** [comment]
hooligan495: Should any action be taken on this one, or is this entirely on the Jruby team and the 1.6 release now?  Not sure if this can be closed or not...

**Comment by hooligan495** [comment]
It should be fixed in the 1.6 Release.  It was a bug in their parser.

**Comment by abedra** [comment]
Is this fixed now?

**Comment by denofevil** [comment]
Yep, it's fixed in JRuby
