### ISSUE TITLE
rcov.gemspec:1: warning: already initialized constant PKG_FILES

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [relevance/rcov#57]
Getting this everytime i start something (cucucmber, gem install, bundler, rails,...).

ruby 1.9.2dev (2010-07-11 revision 28618) [x86_64-darwin10]
Rails 3.0.0.rc

**Comment by jwoertink** [comment]
Is this going to be fixed? I just installed the gem today, and I'm getting this error.

**Comment by bobbrez** [comment]
I am also seeing this error. Is there a workaround / solution to this?

**Comment by bradical** [comment]
Me too but the message varies slightly:
    rcov.gemspec:28: warning: already initialized constant PKG_FILES

**Comment by abedra** [comment]
Is this still an issue? If so can you please provide steps to reproduce?

**Comment by bradical** [comment]
I'm using:
ree-1.8.7-2011.03
bundler-1.0.21
rcov-0.9.9
rails-3.0.10

and this issue appears to have gone away.

**Comment by abedra** [comment]
Ok thanks
