### ISSUE TITLE
Messy output

### ISSUE THREAD

**Issue by ghost** [relevance/rcov#6]
Any idea what&rsquo;s causing this messy output?

http://70.85.173.194/Screenshot.png

My actual code doesn&rsquo;t have most of the line breaks you see in the screenshot.

Here&rsquo;s my rake task:

  require &rsquo;rcov/rcovtask&rsquo;

  namespace :test do
    namespace :coverage do
      desc &rsquo;Delete aggregate coverage data.&rsquo;
      task( :clean ){ rm_f &rsquo;coverage.data&rsquo; }
    end
    desc &rsquo;Aggregate code coverage for unit, functional and integration tests&rsquo;
    task :coverage => &rsquo;test:coverage:clean&rsquo;
    %w[ unit functional ].each do |target|
      namespace :coverage do
        Rcov::RcovTask.new( target ) do |t|
          t.libs << &rsquo;test&rsquo;
          t.test_files = FileList[ "test/#{ target }/*_test.rb" ]
          t.output_dir = "public/coverage/#{  target }"
          t.verbose = true
          t.rcov_opts << "--sort coverage --exclude gem,oci8 --rails --aggregate coverage.data"
        end
      end
      task :coverage => "test:coverage:#{ target }"
    end
  end

[original LH ticket](http://relevance.lighthouseapp.com/projects/16869/tickets/6)

 This ticket has 0 attachment(s).

**Comment by ghost** [comment]
**Messy output**

Which gem are using?  (rcov, or spicycode-rcov from github?)   Also, what platform are you running on?

 by Chad Humphries

**Comment by ghost** [comment]
**Messy output**

gem list --local |grep rcov
rcov (0.8.1.2.0)

uname -a
Linux donaldg 2.6.27-11-generic #1 SMP Thu Jan 29 19:24:39 UTC 2009 i686 GNU/Linux

> ruby -v
> ruby 1.8.7 (2008-08-11 patchlevel 72) [i486-linux]

 by Greg Donald

**Comment by ghost** [comment]
**Messy output**

I would install the spicycode-rcov gem from github.com (gem install spicycode-rcov --source=http://gems.github.com) and it should alleviate most of the issues you are seeing.

 by Chad Humphries

**Comment by ghost** [comment]
**Messy output**

It installed fine, but it doesn&rsquo;t run:

> /usr/lib/ruby/gems/1.8/gems/spicycode-rcov-0.8.1.5.0/bin/rcov
> /usr/lib/ruby/gems/1.8/gems/spicycode-rcov-0.8.1.5.0/bin/rcov:19:in `require&rsquo;: no such file to load -- rcov/version (LoadError)
>         from /usr/lib/ruby/gems/1.8/gems/spicycode-rcov-0.8.1.5.0/bin/rcov:19

 by Greg Donald

**Comment by ghost** [comment]
**Messy output**

Hi

Please try grabbing the latest version 0.8.1.5.6 -- it should install clean.

Rob

 by Rob Sanheim

**Comment by ghost** [comment]
**Messy output**

It does install clean, that is not the issue.

Using it after the install fails, and is still failing in 0.8.1.5.6

> rake test:coverage
> (in /rails/foo)
> rm -f coverage.data
> rm -r public/coverage/unit
> /usr/bin/ruby1.8 -Ilib:test -S rcov --text-report --sort coverage --exclude gem,oci8 --rails --aggregate coverage.data -o "public/coverage/unit" "test/unit/agroup_subject_test.rb""test/unit/ugroup_test.rb" "test/unit/user_ugroup_test.rb" "test/unit/ugroup_permission_test.rb" "test/unit/bookmark_test.rb" "test/unit/user_preference_test.rb" "test/unit/groupset_test.rb" "test/unit/population_study_test.rb" "test/unit/subject_test.rb" "test/unit/population_test.rb" "test/unit/group_subject_test.rb" "test/unit/disease_study_test.rb" "test/unit/disease_test.rb" "test/unit/group_test.rb" "test/unit/people_address_test.rb" "test/unit/site_test.rb" "test/unit/address_test.rb" "test/unit/study_subject_test.rb" "test/unit/person_test.rb" "test/unit/permission_test.rb" "test/unit/study_test.rb" "test/unit/user_test.rb" "test/unit/preference_test.rb" "test/unit/analysis_group_test.rb"
> /usr/lib/ruby/gems/1.8/gems/spicycode-rcov-0.8.1.5.6/bin/rcov:19:in `require&rsquo;: no such file to load -- rcov/version (LoadError)
>         from /usr/lib/ruby/gems/1.8/gems/spicycode-rcov-0.8.1.5.6/bin/rcov:19
> rake aborted!
> Command failed with status (1): [/usr/bin/ruby1.8 -Ilib:test -S rcov --text...]

(See full trace by running task with --trace)

 by Greg Donald

**Comment by ghost** [comment]
**Messy output**

And I&rsquo;d think you would want to wait until an issue is actually resolved before marking it resolved.

 by Greg Donald

**Comment by ghost** [comment]
**Messy output**

Hi Greg

I&rsquo;ll try to reproduce.  I know we are using this version fine for all our builds, so I&rsquo;m not sure what is going on.

Actually, do you have rubygems setup for your environment?

```
$ env |grep rubygem
RUBYOPT=rubygems
```

 by Rob Sanheim

**Comment by ghost** [comment]
**Messy output**

Setting RUBYOPT=rubygems in my environment works.  It&rsquo;d be nice if this weren&rsquo;t required however.

The messy output looks fine now.

 by Greg Donald

**Comment by spicycode** [comment]
Resolved
