### ISSUE TITLE
Integers in multiline strings

### ISSUE THREAD

**Issue by DanielHeath** [relevance/rcov#63]
Multiline single quote strings are not recognized correctly if one of the lines ends in an integer.

For instance:
    latest_version_sql = '(published = ?) or
      ((published = ?) and
        not exists (
          select 1
          from localisations
        )
      )'

**Comment by abedra** [comment]
Is this still an issue for you? If so, can you please submit this again with a test case, the version of ruby and patchlevel you are running, the operating system, and version of gcc you are using?

**Comment by DanielHeath** [comment]
No, I haven't run across it again.
- Daniel

On Wed, Jan 18, 2012 at 2:09 PM, Aaron Bedra
reply@reply.github.com
wrote:
