### ISSUE TITLE
Filename and coverage threshold filtering is slow

### ISSUE THREAD

**Issue by wapcaplet** [relevance/rcov#64]
In the index.html report generated by RCov, when I select a file filter or code coverage filter, the filtering process is very slow (taking 15-20 seconds to filter a large report).

The Javascript code that does the filtering iterates across every row in the table, then does a split() and indexOf() on the row's class string to check whether both filter classes are present. JQuery already has better and more efficient methods for doing this sort of thing.

I've created a patch in my fork which works much better--it only takes a couple seconds to apply filtering to large reports:

https://github.com/wapcaplet/rcov/commit/19cbd05687ade1c8194a6839e04acce1548b0a23

**Comment by wapcaplet** [comment]
Submitted pull request: https://github.com/relevance/rcov/pull/68

**Comment by abedra** [comment]
Great thanks! I'll take a look at this this weekend and apply/release if it looks good
