### ISSUE TITLE
Error installing gem on ubuntu under rvm

### ISSUE THREAD

**Issue by jdonelan** [relevance/rcov#73]
Running into an issue trying to install the relevance-rcov gem on ubunut (under rvm). I can't seem to get a better stack trace than one below (which is useless):

ERROR:  While executing gem ... (TypeError)
     can't dup NilClass

Ruby: 1.8.7
Gem: 1.6.2
Ubuntu: 9.10 Karmic Koala

TRACE:

GET http://rubygems.org/latest_specs.4.8.gz
302 Moved Temporarily
GET http://production.s3.rubygems.org/latest_specs.4.8.gz
200 OK
GET http://gems.github.com/latest_specs.4.8.gz
304 Not Modified
Installing gem relevance-rcov-0.9.2.1
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/bin/rcov
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/lowlevel.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/version.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/rcovtask.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/formatters.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/call_site_analyzer.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/code_coverage_analyzer.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/coverage_info.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/differential_analyzer.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/file_statistics.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/formatters/base_formatter.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/formatters/full_text_report.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/formatters/html_erb_template.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/formatters/html_coverage.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/formatters/text_coverage_diff.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/formatters/text_report.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/formatters/text_summary.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/formatters/failure_report.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/templates/index.html.erb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/templates/detail.html.erb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/templates/screen.css
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/templates/print.css
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/templates/rcov.js
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/templates/jquery-1.3.2.min.js
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib/rcov/templates/jquery.tablesorter.min.js
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/ext/rcovrt/extconf.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/ext/rcovrt/1.8/rcovrt.c
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/ext/rcovrt/1.9/rcovrt.c
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/ext/rcovrt/1.8/callsite.c
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/ext/rcovrt/1.9/callsite.c
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/LICENSE
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/Rakefile
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/doc/readme_for_rake.markdown
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/doc/readme_for_vim.markdown
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/doc/readme_for_emacs.markdown
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/doc/readme_for_api.markdown
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/THANKS
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/test/functional_test.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/test/file_statistics_test.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/test/assets/sample_03.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/test/assets/sample_05-new.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/test/code_coverage_analyzer_test.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/test/assets/sample_04.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/test/assets/sample_02.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/test/assets/sample_05-old.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/test/assets/sample_01.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/test/turn_off_rcovrt.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/test/call_site_analyzer_test.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/test/assets/sample_05.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/editor-extensions/rcov.vim
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/editor-extensions/rcov.el
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/setup.rb
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/BLURB
Building native extensions.  This could take a while...
/home/bamboo/.rvm/rubies/ruby-1.8.7-p334/bin/ruby extconf.rb
creating Makefile

make
gcc -I. -I/home/bamboo/.rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/x86_64-linux -I/home/bamboo/.rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/x86_64-linux -I1.8/   -fPIC -g -O2  -fPIC   -c 1.8/rcovrt.c
gcc -I. -I/home/bamboo/.rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/x86_64-linux -I/home/bamboo/.rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/x86_64-linux -I1.8/   -fPIC -g -O2  -fPIC   -c 1.8/callsite.c
gcc -shared -o rcovrt.so rcovrt.o callsite.o -L. -L/home/bamboo/.rvm/rubies/ruby-1.8.7-p334/lib -Wl,-R/home/bamboo/.rvm/rubies/ruby-1.8.7-p334/lib -L.  -rdynamic -Wl,-export-dynamic    -Wl,-R -Wl,/home/bamboo/.rvm/rubies/ruby-1.8.7-p334/lib -L/home/bamboo/.rvm/rubies/ruby-1.8.7-p334/lib -lruby  -lrt -ldl -lcrypt -lm   -lc

make install
/usr/bin/install -c -m 0755 rcovrt.so /home/bamboo/.rvm/gems/ruby-1.8.7-p334/gems/relevance-rcov-0.9.2.1/lib
/home/bamboo/.rvm/gems/ruby-1.8.7-p334/bin/rcov
ERROR:  While executing gem ... (TypeError)
     can't dup NilClass

**Comment by rurounijones** [comment]
Getting the same error.

Ruby 1.8.7
Gem 1.6.2
Kubuntu 10.04 64bit
rvm 1.5.2

A hack workaround is (if you can) install using system ruby then copy the gem dir and gemspec files to your gemset gems folder

**Comment by jacklin10** [comment]
I'm also seeing this error, but on snow leopard
ruby 1.9.2p180
rvm 1.6.5

**Comment by st23am** [comment]
Same error on snow leopard 
ruby ree-1.8.7-2010.02 [ x86_64 ]
rvm 1.6.20

**Comment by abedra** [comment]
@jacklin10 you should move to simple-cov on 1.9.2. RCov won't work properly past 1.8.7

**Comment by abedra** [comment]
Nobody should be trying to install relevance-rcov anymore.  This is a very old version.  gem install rcov is all that is needed as the relevance version of rcov is the canonical version according to rubygems.org
