### ISSUE TITLE
rcov doesn't work with Kernel.fork

### ISSUE THREAD

**Issue by bronson** [relevance/rcov#77]
Example script:

```
fork do
    puts "two"
end 
puts "one"
```

Run it with `rcov -x rcov script.rb -t`.  You will only see 75% coverage even though clearly every line gets executed.  This is the output:

```
100.0%   1 file(s)   4 Lines   4 LOC
75.0%   1 file(s)   4 Lines   4 LOC
```

It appears that the correct result is replaced with the incorrect one:

Is there any way to run rcov so that a program that forks can still show 100% coverage?  Thanks!

**Comment by abedra** [comment]
Not under the current implementation of RCov.  After a fork, the callsites won't return properly and the markers won't be added to the coverage totals.

**Comment by bronson** [comment]
That makes sense.  Thanks for the explanation!
