### ISSUE TITLE
Jruby file being included in report

### ISSUE THREAD

**Issue by rurounijones** [relevance/rcov#79]
I am running a Rails 3.1.0.rc4 application on jruby 1.6.3 on Kubuntu 10.04.

Using rspec and rake spec:rcov results in a report file that includes the file:

```
jsignal_internal
```

Naturally this is not a file in my project, it looks like some internal jruby thing dealing with signals (SIGHUP etc.)). I can provide the report page if needed.

Rails 1.3.0 rc4
rcov 0.9.9 java
rspec 2.6.0

**Comment by rpocklin** [comment]
Got exactly the same problem with Jruby + rcov (Ubuntu 11.04)

jruby 1.6.3
rails 3.0.10
rspec 2.6.0
rcov 0.9.10-java

Still works fine, but this entry throws total coverage off.

**Comment by leckylao** [comment]
I have exclude it by using this, hope it helps.

```
  t.rcov_opts << "--exclude Gemfile,osx\/objc,gems\/,spec\/,yaml,yaml\/,rubygems/*,jruby/*,parser*,gemspec*,eval*,recognize_optimized*,(__FORWARDABLE__),(erb),C,D"
```

**Comment by abedra** [comment]
This file can be excluded like @lecky mentioned.

**Comment by rurounijones** [comment]
Is there any reason this cannot be added to the default list so we don't have to redefine the default rake task?

**Comment by abedra** [comment]
Please feel free to submit a patch
