### ISSUE TITLE
rcov dosen't install under rubinius

### ISSUE THREAD

**Issue by tjeden** [relevance/rcov#80]
I'm trying to install rcov under Rubinius on Ubuntu

```
rvm install rbx
rvm 
gem install rcov
```

And I've got:

<pre>

Building native extensions.  This could take a while...
ERROR:  Error installing rcov:
    ERROR: Failed to build gem native extension.

        /home/aleks/.rvm/rubies/rbx-master/bin/rbx extconf.rb
creating Makefile

make
gcc -I. -I/home/aleks/.rvm/rubies/rbx-master/include -I/home/aleks/.rvm/rubies/rbx-master/include -I1.8/  -fPIC -ggdb3 -O2 -fPIC  -c 1.8/callsite.c
1.8/callsite.c:2:17: error: env.h: No such file or directory
1.8/callsite.c:3:18: error: node.h: No such file or directory
1.8/callsite.c: In function ‘callsite_custom_backtrace’:
1.8/callsite.c:73: error: ‘ruby_frame’ undeclared (first use in this function)
1.8/callsite.c:73: error: (Each undeclared identifier is reported only once
1.8/callsite.c:73: error: for each function it appears in.)
1.8/callsite.c:75: error: ‘NODE’ undeclared (first use in this function)
1.8/callsite.c:75: error: ‘n’ undeclared (first use in this function)
1.8/callsite.c:81: error: dereferencing pointer to incomplete type
1.8/callsite.c:81: error: ‘ID_ALLOCATOR’ undeclared (first use in this function)
1.8/callsite.c:82: error: dereferencing pointer to incomplete type
1.8/callsite.c:85: error: dereferencing pointer to incomplete type
1.8/callsite.c:85: error: dereferencing pointer to incomplete type
1.8/callsite.c:86: error: dereferencing pointer to incomplete type
1.8/callsite.c:86: error: dereferencing pointer to incomplete type
1.8/callsite.c:87: error: dereferencing pointer to incomplete type
1.8/callsite.c:89: error: dereferencing pointer to incomplete type
1.8/callsite.c:89: error: dereferencing pointer to incomplete type
1.8/callsite.c:94: error: dereferencing pointer to incomplete type
1.8/callsite.c: At top level:
1.8/callsite.c:113: error: expected ‘)’ before ‘event’
1.8/callsite.c: In function ‘cov_install_callsite_hook’:
1.8/callsite.c:151: error: ‘coverage_event_callsite_hook’ undeclared (first use in this function)
1.8/callsite.c:151: error: ‘RUBY_EVENT_CALL’ undeclared (first use in this function)
1.8/callsite.c: In function ‘cov_remove_callsite_hook’:
1.8/callsite.c:163: error: ‘coverage_event_callsite_hook’ undeclared (first use in this function)
make: *** [callsite.o] Error 1
</pre>

Should I post it on Rubinius issues?

**Comment by rsanheim** [comment]
Rcov is MRI specific, and 1.8.6/7 specific as well.  For coverage on rubinius you would need something specific to their VM implementation.
