### ISSUE TITLE
rcov skips a source file when run under bundler via bundle exec

### ISSUE THREAD

**Issue by mbklein** [relevance/rcov#81]
### Note

I originally filed this as a [bug in bundler](https://github.com/carlhuda/bundler/issues/1344), but received a response saying "Thanks for filing such a detailed report. Unfortunately, we don't have the time to debug other gems right now. We may get to this later but in the mean time I suggest filing this with rcov and isolating where in rcov it's being affected by bundler."

I honestly haven't been able to figure out if the bug is in bundler or rcov, but it's probably worth looking into from both sides. If someone can trace it back to bundler, I'd be happy to toss it back to them with more info (or, better yet, fix it and submit a patch).
### Description

One file is missing from my rcov coverage report when I run rcov using `bundle exec` instead of on its own. I've done everything I can to minimize outside interference, including wiping out my global gemset (except for bundler) and even my system gems.
### Environment

`bundle config` is empty.
Bundler version: `Bundler version 1.0.17`
RCov version: `rcov 0.9.10 2010-02-28`
RSpec version: `rspec 1.3.2` (though it also happens under 2.x)
Ruby version: `ruby 1.8.7 (2011-06-30 patchlevel 352) [i686-darwin10.8.0]`
Rubygems version: `1.8.6`
RVM: `rvm 1.6.32 by Wayne E. Seguin (wayneeseguin@gmail.com) [https://rvm.beginrescueend.com/]`
global gemset contains nothing but bundler
project gemset is empty before `bundle install`
### Steps to reproduce
1. Clone the [small example repo](https://github.com/mbklein/bundler-rcov-bug).
2. Trust the .rvmrc file.
3. `bundle install`
4. `rcov -T -Ilib:spec --exclude gems/*,spec/*,ruby/* spec/*_spec.rb spec/**/*_spec.rb`
5. 4 examples run and pass, and all three source files under `lib` were checked for coverage.
6. `bundle exec rcov -T -Ilib:spec --exclude gems/*,spec/*,ruby/* spec/*_spec.rb spec/**/*_spec.rb`
7. Same 4 examples run and pass, but only two files were checked for coverage.
### Notes
1. I first noticed the issue while running the rspec/rcov rake tasks, but once I traced it to bundle exec, I took rake out of the equation for simplicity's sake.
2. I tried rspec 2.6 as well, and got the same result.
3. `which rcov` and `bundle exec which rcov` point to the same executable.

**Comment by nathanvda** [comment]
Wow. Good work. We are experiencing the same troubles: some files are not being picked up by rcov wen running the `spec:rcov` task. 

I will try to have a look at your example repo.

**Comment by leckylao** [comment]
I am using this code the include those missing files, hope it helps:

t.rcov_opts << "--include-file #{missing_files}"

**Comment by abedra** [comment]
Interesting. @lecky is correct to point out the option to add missing files, but things shouldn't disappear. I'll look into this and see if I can pinpoint it to anything in RCov. My thoughts are that since this has never been an issue before, it is probably on bundler to handle.

**Comment by abedra** [comment]
I cloned your repository and setup a Rakefile.  Here's what I put inside

<pre>
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:rcov) do |t|
  t.pattern = 'spec/**/*_spec.rb'
  t.rcov = true
  t.rcov_opts = %w{--rails --exclude gems/*,spec/*,ruby/* spec/*_spec.rb spec/**/*_spec.rb}
end
</pre>


Everything worked fine. I pulled the latest RSpec in as well. At this point things seem to function properly. If this problem happens to intersect with RSpec 1, then it will end up staying that way. Hope this helps.
