### ISSUE TITLE
Use File::PATH_SEPARATOR instead of ":"

### ISSUE THREAD

**Issue by dchelimsky** [relevance/rcov#83]
Any reason not to use File::PATH_SEPARATOR instead of ":"? Windows users are accustomed to using ";" as a path separator and this has led to some confusion for rspec users. Originally we had ":". Then we changed it to File::PATH_SEPARATOR based on a pull request. Then we realized that broke rcov in Windows, so there is an unreleased commit changing that back to ":", but I think a fair argument can be made that rcov should use File::PATH_SEPARATOR instead.

**Comment by sundbp** [comment]
I was the one reporting this on the rspec side. I'd agree using a consistent PATH_SEPARATOR for rcov would be a good alternative.

The one downside to using platform dependent separators on commandline arguments is documentation/blogs/etc can be confusing for users (i.e. cut and paste from example doesn't work).

**Comment by rsanheim** [comment]
I should be able to look into this this Friday.

**Comment by rsanheim** [comment]
I looked into this a little and didn't see where a literal ":" was being
used -- can you point out where you saw that?  I did see PATH_SEPARATOR
being used in rcovtask.rb, which is correct...

**Comment by dchelimsky** [comment]
Check out https://github.com/relevance/rcov/blob/master/bin/rcov#L88-90

**Comment by rsanheim** [comment]
Ah thanks, was looking in the wrong spot.
