### ISSUE TITLE
fail to install on ruby-head 2.0

### ISSUE THREAD

**Issue by zhangpy** [relevance/rcov#84]
$ruby -v
ruby 2.0.0dev (2011-10-26 trunk 33526) [i686-linux](OS: Ubuntu 11.10)

$ gem install rcov
Fetching: rcov-0.9.11.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing rcov:
    ERROR: Failed to build gem native extension.

```
    .rvm/rubies/ruby-head/bin/ruby extconf.rb
```

creating Makefile

make
compiling 1.8/rcovrt.c
1.8/rcovrt.c:2:17: fatal error: env.h: No such file or directory
compilation terminated.
make: **\* [rcovrt.o] Error 1

**Comment by drbrain** [comment]
I'm also experiencing this issue.  Due to the "1.8" looks like there's an inadequate version check:

```
Building native extensions.  This could take a while...
rake aborted!
ERROR: Failed to build gem native extension.

        /usr/local/bin/ruby20 extconf.rb
creating Makefile

make
compiling 1.8/callsite.c
1.8/callsite.c:2:10: fatal error: 'env.h' file not found
#include <env.h>
         ^
1 error generated.
make: *** [callsite.o] Error 1


Gem files will remain installed in /Users/drbrain/Work/git/rubygems/tmp/isolate/ruby-1.9.1/gems/rcov-0.9.11 for inspection.
Results logged to /Users/drbrain/Work/git/rubygems/tmp/isolate/ruby-1.9.1/gems/rcov-0.9.11/ext/rcovrt/gem_make.out
```

**Comment by drbrain** [comment]
The check in the extconf.rb is wrong:

https://github.com/relevance/rcov/blob/master/ext/rcovrt/extconf.rb#L8

Should be `if RUBY_VERSION > "1.9"`

Same for https://github.com/relevance/rcov/blob/master/ext/rcovrt/extconf.rb#L15

**Comment by abedra** [comment]
1.9+ support has been completely removed. If you are on 1.9 or higher, you should be using simplecov

**Comment by fahimbabarpatel** [comment]
facing same issue
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

```
    /home/.rvm/rubies/ruby-2.0.0-p0/bin/ruby extconf.rb 
```

creating Makefile

make
compiling 1.8/rcovrt.c
1.8/rcovrt.c:2:17: fatal error: env.h: No such file or directory
compilation terminated.
make: **\* [rcovrt.o] Error

**Comment by rennhak** [comment]
If you run into this problem make sure to install the simplecov-rcov gem which provides the needed env.h for the latter ruby versions.

**Comment by benallfree** [comment]
@rennhak Installing simplecov-rcov didn't fix the env.h problem for me on OS X 10.9

**Comment by abedra** [comment]
You need to switch to simplecov completely. RCov won't work properly in 2.0 or 1.9
