### ISSUE TITLE
Rcov doesn't report coverage on content of some methods, but got covered on the def

### ISSUE THREAD

**Issue by leckylao** [relevance/rcov#88]
http://www.flickr.com/photos/73883639@N05/6663551041/in/photostream/

As showed above, many places of the report showing that some method's content didn't get cover but the def got covered.... It's really weird. Anyone has the same issue?

**Comment by samumbach** [comment]
If the file is loaded during the test, all def's and other code outside of methods (class definitions, constants, etc) are evaluated and considered to be covered.

**Comment by abedra** [comment]
@sumbach should we consider this issue closed, or is it really a defect?

**Comment by ghost** [comment]
@sumbach , you are right. However I found other issue that some code didn't cover for some reason. Haven't figure out yet. But this one can be close.

**Comment by leckylao** [comment]
@sumbach , you are right. However I found other issue that some code didn't cover for some reason. Haven't figure out yet. But this one can be close.
