### ISSUE TITLE
rcov 1.0 does not install on jruby

### ISSUE THREAD

**Issue by atambo** [relevance/rcov#90]
When upgrading from rcov 0.9.11 to rcov 1.0 the gem install fails. Here is the output I get when trying to gem install rcov on jruby:

https://gist.github.com/1684946

**Comment by atambo** [comment]
My bet is the java platform gem was never pushed to rubygems: http://rubygems.org/gems/rcov/versions

**Comment by rsanheim** [comment]
Paging @abedra, paging @abedra to the rcov.

**Comment by abedra** [comment]
Yes, RCov 1.0 does not work on JRuby yet. I did not push a -java version of the gem, so if you tried to install it, it most likely grabbed the wrong one. There are some things that broke in JRuby land along with some rcov compilation changes that need to be fixed before this will work again. Please continue to use 0.9.11. Nothing changed for JRuby between then and 1.0 anyways, so you aren't missing out on anything
