### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by paulvt** [relevance/rcov#96]
Hi!
I'm packaging rcov for Debian and would be greatly helped by a `release_1_0_0` release tag and also future release tags. As the gem doesn't seem to contain more than `lib/` and `bin/` as of the 1.0.0 release, I cannot really use it as upstream source anymore.  If there is another place where I could fine release tarballs, that is also fine.

Thanks in advance,
Cheers,

Paul

**Comment by abedra** [comment]
Certainly! The only drawback here is that the current 1.0 doesn't support JRuby. I still need to put things back in place there.

**Comment by paulvt** [comment]
Ah ok, I've been trying to use 0.9.11, but it has test problems for Ruby 1.8.7 and I saw some commits to fix in the timeline.

**Comment by abedra** [comment]
Yes. In 1.0 tests for mri/ree 1.8.7 should be good.

**Comment by paulvt** [comment]
Great, then I await the 1.0.0 release tag.  Cheers.

**Comment by paulvt** [comment]
Hi! Sorry to be a bit of a bother, but if you don't think an official 1.0.0 release with tag and all is will happen within the week, please let me know. In that case I will package a git snapshot from the repository.

**Comment by abedra** [comment]
I will have this done by tomorrow afternoon. Sorry for the delay.

**Comment by paulvt** [comment]
Thanks! I see the 1.0 tag is there.
